### ISSUE TITLE
How to add a new micro app in this demo? 

### ISSUE THREAD

**Issue by hunter-xue** [easyops-cn/next-demo#11]
I created a new subfolder "micro-apps/my-demo", and then storyboard.yaml, package.json... follow todo app, but it dose not work...

**Comment by weareoutman** [comment]
You can try to run `yarn` in the repo root, after you manually create a micro-app. Which will do a *mono-repo initialization*, then your new micro-app will work.

By the way, we should run `yarn yo` to create a new micro-app, which will run `yarn` automatically. But there is no document about it right now, because the `yarn yo` currently doesn't support to create a yaml storyboard (only json).

Once we support creating micro-apps with yaml storyboard, we will update the docs, thank you.

**Comment by hunter-xue** [comment]
> You can try to run `yarn` in the repo root, after you manually created a micro-app. Which will do a _mono-repo initialization_, then your new micro-app will work.
> 
> By the way, we should run `yarn yo` to create a new micro-app, which will run `yarn` automatically. But there is no document about it right now, because the `yarn yo` currently doesn't support to create a yaml storyboard (only json).
> 
> Once we support creating micro-apps with yaml storyboard, we will update the docs, thank you.

It works! and thanks a lot. Add this technique to README will more helpful. :)
